# Source: https://dev.to/andresfmoya/install-jenkins-using-docker-compose-4cab
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    build: .
    privileged: true
    user: root
    environment:
      - VIRTUAL_HOST=jenkins.thaivd.com
      - LETSENCRYPT_HOST=jenkins.thaivd.com
      - LETSENCRYPT_EMAIL=jenkins@thaivd.com
      - VIRTUAL_PORT=8088
    ports:
      - 8088
      - 50000
      - 443
    container_name: jenkins
    volumes:
      - ./run_env/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - ~/.docker/cli-plugins/docker-compose:/usr/bin/docker-compose
    networks:
     - "mlops-net"

networks:
  mlops-net:
    external: true